CREATE TABLE order_items(
 id INT PRIMARY KEY AUTO_INCREMENT,
 COUNT INT NOT NULL,
 amount DOUBLE(11,2) NOT NULL ,
 title VARCHAR(100) NOT NULL,
 author VARCHAR(100) NOT NULL,
 price DOUBLE(11,2) NOT NULL,
 img_path VARCHAR(100) NOT NULL,
 order_id VARCHAR(100) NOT NULL,
 FOREIGN KEY(order_id) REFERENCES  orders(id)
)
